### ISSUE TITLE
What is the expected implementation on non-browser run-times?

### ISSUE THREAD

**Issue by sunfishcode** [wingo/stringrefs#30]
The proposal answers this question as:

> Assuming that the non-browser implementation uses WTF-8 as the native string representation, then a stringref is a pointer, a length, and a reference count.

However, the proposal previously also said:

> Don't provide a `concat` / `append` interface.  Because JS engines would implement this via rope strings, this would encode an     expectation that rope strings are necessary. 

This text is now gone, and the proposal now seeks to add a `concatenate` operation. This suggests an expectation that rope strings will now be necessary.

**Comment by sunfishcode** [comment]
The spec never makes complexity guarantees, about anything. That doesn't mean they don't exist in practice though.

Consider an application that needs to concatenate a large number of strings into one big string. Should it invoke `concat` once for each? That might take O(N) time on certain engines and work fine. In an engine that uses "pointer, length, reference count" for `stringref`, doing that might take O(N**2) time and be unusably slow.

**Comment by wingo** [comment]
Doing a round-up on issues -- concatenation was added in #36.  I think this issue is still open though as the text cited in https://github.com/wingo/stringrefs/issues/30#issue-1130150002 is still present.
