### ISSUE TITLE
Minor tuning: `get_and_advance_wtf8`

### ISSUE THREAD

**Issue by jakobkummerow** [wingo/stringrefs#32]
For WTF-8, advancing a position needs to duplicate some of the work that retrieving a codepoint also needs to do. We could hope for "sufficiently smart" engines to eliminate this duplication, or we could offer a combined instruction:
```
(string.get_and_advance_wtf8 str:stringref pos:i32)
  -> codepoint:i32, newpos:i32
```
which would return the codepoint at the WTF-8 *`pos`* in *`str`* as an i32, and the position of the next codepoint (i.e. *`newpos`* is equivalent to `(string.advance_wtf8 str pos 1)`).

(Probably not important; just leaving this idea here before I forget about it.)

**Comment by wingo** [comment]
After #36, the way to iterate codepoint by codepoint is `stringview_iter`, which is not tied to WTF-8 and keeps its "cursor" state hidden.  But, `stringview_iter.next` might be a nice addition, being `stringview_iter.cur` plus `stringview_iter.advance`

**Comment by wingo** [comment]
Continuation ⇒ https://github.com/WebAssembly/stringref/issues/4
