### ISSUE TITLE
Minor feature: toUpperCase/toLowerCase

### ISSUE THREAD

**Issue by jakobkummerow** [wingo/stringrefs#35]
In another discussion, the observation was raised that converting characters to upper or lower case requires a rather large ICU database. Since many embedders (in particular: browsers) have those already, it would be nice to offer these conversions (either per-codepoint or per-string or both) as built-in features so that Wasm modules don't have to ship their own unicode tables.

This could, of course, be a post-MVP feature; and at any rate it can definitely wait until the fundamental design is hashed out solidly. Just recording the idea here.

**Comment by wingo** [comment]
Good point.  It is quite silly to have multiple copies of ICU tables all over the place.

One question would be, the ICU database changes over time.  Would it change for character mapping?  Would we be OK with the result of toUpperCase etc changing over time?

**Comment by wingo** [comment]
Thinking about this some more, I think it might be reasonable to call out to a run-time library for anything that might depend on the ICU database.  This allows the ICU database to change over time.  Stringrefs facilitate the construction of such a run-time library by providing a common data type.  When targetting the web, just using Intl or other JS facilities is probably the way to go.

**Comment by wingo** [comment]
Moved: https://github.com/WebAssembly/stringref/issues/5
