### ISSUE TITLE
Add concatenation / substring ?

### ISSUE THREAD

**Issue by wingo** [wingo/stringrefs#4]
JavaScript implementations all have support for ropes and slices, to concatenate or take a substring without creating a new array of characters.  This is a capability of the platform.  Should we aim to expose it to WebAssembly?

Pros:
 - Improves wasm platform expressivity
 - Avoids a callout to JS for users that really need it
 - Avoid users building their own ropes/slices; facilitates interop
 - Side effects of concat/substring would be legible to optimizing compilers, unlike call to import

Cons:
 - Maybe unnecessary?  Users can just call to JS if they know their embedding
 - Raises the implementation requirements for non-browser WebAssembly

**Comment by gsnedders** [comment]
FWIW: I think we should come up with a definition of what we think the MVP is, and then the answer as to whether the MVP includes concat/slicing should fall out of that decision.

I (as someone with Opinions about strings) am strongly in favour of including these in WASM, but I don't think they necessarily have to be there from day one in the WASM case. But I should probably write up something longer going through my thoughts here at some point.

**Comment by wingo** [comment]
A common theme in feedback has been that we should include ropes and slices.  My motivation for omitting them was implementation burden for non-browser WebAssembly which doesn't already have rope/slice strings, but my understanding is that these implementors are OK with ropes/slices if they are useful.  I understand also that compilers/runtimes targetting WebAssembly would also take advantage of this facility.  Therefore I think we should bite the bullet and add a `string.concat` and `string.slice` or so.  The tricky concern is what to do when slicing between UTF-16 code units; assuming that we want Dart and Java to use WebAssembly strings, then we need to ensure that we provide a suitable target for the relevant string operations, and that includes creating isolated surrogates.  So, let's punt on the resolution of this issue until we fully resolve the UTF-16 issue.

**Comment by wingo** [comment]
Concatenation and substring added in https://github.com/wingo/stringrefs/pull/36.
