### ISSUE TITLE
Ambiguity in the description of stringview_iter

### ISSUE THREAD

**Issue by sunfishcode** [wingo/stringrefs#42]
`stringview_iter` is desecribed as "an iterator over the `codepoints` in str". However, this could have two possible meanings:
 - an iterator over the BMP-range U+0 through U+FFFF codepoints, where surrogate pairs are not resolved
 - an iterator over the USV codepoints U+0 through U+10FFFF, with surrogate pairs resolved into non-BMP codepoints

Given the shape of the proposal, it seems like the first of these is intended. Most uses of codepoint in the proposal seem to be talking about BMP codepoints. However, the document also defines codepoint as "An integer in the range [0,0x10FFFF]", which seems to leave the door open.

**Comment by wingo** [comment]
The intention was the second.  The proposal defines a string as "a sequence of USVs and isolated surrogates".  This is a sequence of codepoints, but excluding surrogate pairs.  This happens to be the set of of codepoint sequences that can be encoded in WTF-16 or WTF-8.  `stringview_iter` iterates over these codepoints.  It only ever uses the term "WTF-16 code units" when referring to 16-bit values.  As a user, one would never see a surrogate pair when accessing interfaces defined in terms of codepoints.  You could however see the two halves when accessing a string via `stringview_wtf16`, but that interface is specified in terms of code units, not code points.

**Comment by wingo** [comment]
Closing as resolved; @sunfishcode if you have more concerns they are welcome, over at https://github.com/WebAssembly/stringref/issues.  Thanks again for your review!
